import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.detekt)
    // composeApp doesn't apply cleanarch.kmp.base (see the detekt comment below), so it needs
    // this applied directly too, same as detekt — specs/014-code-coverage-tooling.
    alias(libs.plugins.kover)
}

/**
 * Generates AppConfig.kt (commonMain) from the resolved backend base URL. A real task class
 * (rather than an ad-hoc `doLast { }`) so its inputs/outputs are configuration-cache-safe — a
 * script-captured closure can't serialize into the cache.
 */
abstract class GenerateAppConfig : DefaultTask() {

    @get:Input
    abstract val authApiBaseUrl: Property<String>

    @get:Input
    abstract val sentryDsn: Property<String>

    @get:Input
    abstract val versionName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val packageDir = outputDir.get().dir("com/connectapp/cleanarch/config").asFile
        packageDir.mkdirs()
        packageDir.resolve("AppConfig.kt").writeText(
            """
            package com.connectapp.cleanarch.config

            // Generated by the :composeApp:generateAppConfig Gradle task — do not edit directly.
            // AUTH_API_BASE_URL comes from connectapp.authApiBaseUrl (gradle.properties, -P, or
            // the CONNECTAPP_AUTH_API_BASE_URL env var). SENTRY_DSN comes from
            // connectapp.sentryDsn/CONNECTAPP_SENTRY_DSN and is empty when unset — Sentry is
            // opt-in (specs/011-crash-analytics-reporting), unlike the mandatory backend URL.
            // VERSION_NAME is the same value assigned to android.defaultConfig.versionName below
            // (releaseVersionName, specs/012-release-pipeline-automation), so Settings' "About"
            // row shows the actual shipped version instead of a hardcoded/blank one.
            // See composeApp/build.gradle.kts.
            internal object AppConfig {
                const val AUTH_API_BASE_URL: String = "${authApiBaseUrl.get()}"
                const val SENTRY_DSN: String = "${sentryDsn.get()}"
                const val VERSION_NAME: String = "${versionName.get()}"
            }

            """.trimIndent()
        )
    }
}

/**
 * Backend base URL, resolved without ever hardcoding it in Kotlin source:
 * -Pconnectapp.authApiBaseUrl=... > $CONNECTAPP_AUTH_API_BASE_URL > gradle.properties default.
 * A real deployment overrides this per environment (dev/staging/prod) from the build invocation —
 * nothing else in this project points at a concrete backend address.
 */
val resolvedAuthApiBaseUrl: String = (providers.gradleProperty("connectapp.authApiBaseUrl").orNull
    ?: providers.environmentVariable("CONNECTAPP_AUTH_API_BASE_URL").orNull)
    ?: error(
        "Missing backend URL: set connectapp.authApiBaseUrl in gradle.properties, " +
            "pass -Pconnectapp.authApiBaseUrl=..., or set CONNECTAPP_AUTH_API_BASE_URL."
    )

// Sentry DSN, resolved the same way but optional (empty string, not an error, when unset) —
// see specs/011-crash-analytics-reporting/quickstart.md § Prerrequisitos.
val resolvedSentryDsn: String = providers.gradleProperty("connectapp.sentryDsn").orNull
    ?: providers.environmentVariable("CONNECTAPP_SENTRY_DSN").orNull
    ?: ""

// Same value the release pipeline overrides android.defaultConfig.versionName with
// (specs/012-release-pipeline-automation) — computed once here so AppConfig.VERSION_NAME and
// the actual Android versionName below never drift apart.
val resolvedVersionName: String = providers.gradleProperty("releaseVersionName").orNull ?: "1.0"

val generateAppConfig = tasks.register<GenerateAppConfig>("generateAppConfig") {
    description = "Generates AppConfig.kt (commonMain) from connectapp.authApiBaseUrl/connectapp.sentryDsn/releaseVersionName."
    authApiBaseUrl.set(resolvedAuthApiBaseUrl)
    sentryDsn.set(resolvedSentryDsn)
    versionName.set(resolvedVersionName)
    outputDir.set(layout.buildDirectory.dir("generated/source/appConfig/commonMain/kotlin"))
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_11)
        }
    }

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "ComposeApp"
            isStatic = true
            // SQLDelight's native-driver (pulled in transitively via :core:database) links
            // against the system libsqlite3 dylib — see core/database/build.gradle.kts.
            linkerOpts += "-lsqlite3"
        }
    }

    sourceSets {
        androidMain.dependencies {
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.activity.compose)

            // Koin para Android
            implementation(libs.koin.android)
        }
        commonMain {
            kotlin.srcDir(generateAppConfig)
        }
        commonMain.dependencies {
            implementation(libs.compose.runtime)
            implementation(libs.compose.foundation)
            implementation(libs.compose.material3)
            implementation(libs.compose.ui)
            implementation(libs.compose.components.resources)
            implementation(libs.compose.uiToolingPreview)
            implementation(libs.androidx.lifecycle.viewmodelCompose)
            implementation(libs.androidx.lifecycle.runtimeCompose)

            // Navigation3 (AppEntryProvider.kt construye NavEntry directamente)
            implementation(libs.navigation3.ui)
            implementation(libs.navigation3.runtime)

            // Acceso a capas del proyecto
            implementation(projects.presentation)
            implementation(projects.domain.auth)
            implementation(projects.domain.orders)
            implementation(projects.domain.settings)
            implementation(projects.domain.analytics)
            implementation(projects.commonResources)
            implementation(projects.core.network)
            implementation(projects.core.storage)
            implementation(projects.core.database)
            implementation(projects.core.notifications)
            implementation(projects.data.auth)
            implementation(projects.data.orders)
            implementation(projects.data.settings)
            implementation(projects.data.analytics)

            // Módulos de feature (composeApp es el único módulo que conoce a todas)
            implementation(projects.feature.splash)
            implementation(projects.feature.login)
            implementation(projects.feature.register)
            implementation(projects.feature.forgotPassword)
            implementation(projects.feature.home)
            implementation(projects.feature.settings)
            implementation(projects.feature.profile)
            implementation(projects.feature.orders)
            implementation(projects.feature.editProfile)
            implementation(projects.feature.privacyPolicy)

            // Núcleo de Koin para KMP
            implementation(libs.koin.core)
            // Extensiones para Compose Multiplatform
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)

        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
        }
    }
}

android {
    namespace = "com.connectapp.cleanarch"
    compileSdk = libs.versions.android.compileSdk.get().toInt()

    defaultConfig {
        applicationId = "com.connectapp.cleanarch"
        minSdk = libs.versions.android.minSdk.get().toInt()
        targetSdk = libs.versions.android.targetSdk.get().toInt()
        // Overridable by the release pipeline (specs/012-release-pipeline-automation) via
        // -PreleaseVersionCode/-PreleaseVersionName, derived from the release tag — defaults
        // keep local/CI (non-release) builds exactly as before.
        versionCode = (providers.gradleProperty("releaseVersionCode").orNull?.toIntOrNull()) ?: 1
        versionName = resolvedVersionName
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    debugImplementation(libs.compose.uiTooling)

    detektPlugins(libs.detekt.formatting)
}

// composeApp doesn't apply cleanarch.kmp.base -- see
// specs/005-static-analysis-ci/plan.md § Complexity Tracking. Same reasoning as that
// convention plugin's detekt {} block for the explicit `source`: no classic single "main"
// source set (KMP), and it keeps generated code (Compose Resources accessors, AppConfig.kt
// under build/generated/...) out of the baseline.
detekt {
    config.setFrom(rootProject.file("config/detekt/detekt.yml"))
    baseline = file("detekt-baseline.xml")
    buildUponDefaultConfig = true
    source.setFrom(
        files("src/commonMain/kotlin", "src/androidMain/kotlin", "src/iosMain/kotlin")
    )
}

