package com.connectapp.core.database

import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.db.SqlSchema

/**
 * Creates the platform-backed [SqlDriver] for a SQLDelight-generated database.
 *
 * [schema] is the `Schema` object generated by the SQLDelight plugin for the caller's own
 * `.sq` files (e.g. `OrdersDatabase.Schema`) — this module defines no schema of its own (see
 * research.md D1 in specs/010-offline-cache-layer): each `data:*` module owns its schema and
 * only borrows this factory for the platform-specific driver plumbing.
 *
 * [databaseName] is the SQLite file name and should be stable across app launches, and distinct
 * per logical database if more than one is ever needed (mirrors `createKVault(name)` in
 * `core:storage`).
 */
expect fun createSqlDriver(schema: SqlSchema<QueryResult.Value<Unit>>, databaseName: String): SqlDriver
